### ISSUE TITLE
Use kubectl -R 

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry-incubator/loggregator-k8s-deployment#8]
https://github.com/cloudfoundry-incubator/loggregator-k8s-deployment/blob/6bd7c16896d6fca27bfb94f651610b46dd83a3c1/deploy.sh#L20

**Comment by jasonkeene** [comment]
Yeah, we tried this. Is there a way to force the ordering of the objects? For instance the namespace needs to be created first, then configmaps/secrets, then the rest of the objects. We wrote the script to control ordering. If we can delete it I would prefer to though.

**Comment by dprotaso** [comment]
I’ve seen teams add a prefix to the file 001, 002

**Comment by jasonkeene** [comment]
That's cool, I haven't seen that before. We are investigating writing an operator for loggregator/log-cache which would handle the ordering of the deploy. I'm happy keeping the script until then. Makes acceptance easier. Thanks for the idea though!
